logging:
  level:
    io.vijaykarthik : DEBUG
    org.springframework: INFO
    
vijay:
  error-code-mapping:
    java.lang.IllegalArgumentException: 401
    io.vijaykarthik.exception.CustomException: 402
  error-message-mapping:
    java.lang.IllegalArgumentException: Invalid Input
    io.vijaykarthik.exception.CustomException: Custom error message